### ISSUE TITLE
ImportError: DLL load failed: 找不到指定的模块。

### ISSUE THREAD

**Issue by jellywen2017** [nladuo/THSTrader#1]
C:\Users\Administrator>python C:\Users\Administrator\Desktop\work\THSTrader\test.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\work\THSTrader\test.py", line 4, in <module>
    from THS.THSTrader import THSTrader
  File "C:\Users\Administrator\Desktop\work\THSTrader\THS\THSTrader.py", line 5, in <module>
    import pandas as pd
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\groupby\__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\groupby\groupby.py", line 49, in <module>
    from pandas.core.frame import DataFrame
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\frame.py", line 74, in <module>
    from pandas.core.series import Series
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\series.py", line 3978, in <module>
    Series._add_series_or_dataframe_operations()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\generic.py", line 8891, in _add_series_or_dataframe_operations
    from pandas.core import window as rwindow
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\window.py", line 36, in <module>
    import pandas._libs.window as _window
ImportError: DLL load failed: 找不到指定的模块。

**Comment by nladuo** [comment]
看日志是pandas装的问题，根本没引进来。试试用anaconda3的python。

**Comment by nladuo** [comment]
https://www.anaconda.com/download/

**Comment by jellywen2017** [comment]
感谢Kalen anaconda3的python没有报错

**Comment by jellywen2017** [comment]
请问有没有方案在无界面的centos上运行THSTrader

**Comment by nladuo** [comment]
没有。这是windows软件。

**Comment by nladuo** [comment]
应该只能用KVM弄个windows虚拟机了。

如果要弄这种交易接口应该要找券商直接对接把，我看也有这样的收费量化平台，数据量更多，而且可以对接期货，不过好像要上传策略。我也是刚刚开始接触量化，自己弄着玩儿。
