### ISSUE TITLE
adbutils.errors.AdbError: unknown host service

### ISSUE THREAD

**Issue by poemon** [nladuo/THSTrader#17]
作者你好，我的python版本3.9，用的是雷电模拟器9，相关包的依赖也安装了
```
adb devices
显示为
List of devices attached
emulator-5554   device
```
但是在运行下列代码时，会出现unknown host service
```
python -m uiautomator2 init
显示为
adbutils.errors.AdbError: unknown host service
```
想问一下这是什么原因导致的，非常感谢，以下是完整显示
```
 python -m uiautomator2 init
[I 230628 00:49:01 init:156] uiautomator2 version: 2.16.23
[I 230628 00:49:01 init:373] Install minicap, minitouch
[D 230628 00:49:01 init:59] Use cached assets: C:\Users\Administrator\.uiautomator2\cache\minitouch-69336c8f34\minitouch
[D 230628 00:49:01 init:238] Push to /data/local/tmp/minitouch:0755
[D 230628 00:49:01 init:59] Use cached assets: C:\Users\Administrator\.uiautomator2\cache\minicap.so-0750876ce8\minicap.so
[D 230628 00:49:01 init:238] Push to /data/local/tmp/minicap.so:0755
[D 230628 00:49:01 init:59] Use cached assets: C:\Users\Administrator\.uiautomator2\cache\minicap-3d0b86b17d\minicap
[D 230628 00:49:01 init:238] Push to /data/local/tmp/minicap:0755
[D 230628 00:49:01 init:256] apk-debug package-info: {'package_name': 'com.github.uiautomator', 'version_name': '2.3.3', 'version_code': 2003003, 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2023, 6, 28, 0, 33, 9), 'last_update_time': datetime.datetime(2023, 6, 28, 0, 33, 9), 'signature': 'ae17cd86], past signatures:['}
[D 230628 00:49:01 init:257] apk-debug-test package-info: {'package_name': 'com.github.uiautomator.test', 'version_name': 'null', 'version_code': 0, 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2023, 6, 28, 0, 33, 9), 'last_update_time': datetime.datetime(2023, 6, 28, 0, 33, 9), 'signature': 'ae17cd86], past signatures:['}
[I 230628 00:49:01 init:391] Already installed com.github.uiautomator apks
[D 230628 00:49:01 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--stop')
[D 230628 00:49:02 init:295] Real version: [0, 10, 0], Expect version: [0, 10, 0]
[D 230628 00:49:02 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--nouia', '-d', '--addr', '127.0.0.1:7912')
[I 230628 00:49:02 init:350] Check atx-agent version
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\py39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\anaconda3\envs\py39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\uiautomator2\__main__.py", line 289, in <module>
    main()
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\uiautomator2\__main__.py", line 279, in main
    actions[args.subparser](args)
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\uiautomator2\__main__.py", line 36, in cmd_init
    init.install()
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\uiautomator2\init.py", line 393, in install
    self.setup_atx_agent()
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\uiautomator2\init.py", line 351, in setup_atx_agent
    self.check_atx_agent_version()
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\retry\api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\uiautomator2\init.py", line 358, in check_atx_agent_version
    port = self._device.forward_port(7912)
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\adbutils\_device.py", line 244, in forward_port
    for f in self.forward_list():
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\adbutils\_device.py", line 252, in forward_list
    c = self.open_transport("list-forward")
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\adbutils\_device.py", line 89, in open_transport
    c.check_okay()
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\adbutils\_adb.py", line 134, in check_okay
    raise AdbError(self.read_string_block())
adbutils.errors.AdbError: unknown host service
```

**Comment by nladuo** [comment]
跑一下adb kill-server再试试？

**Comment by poemon** [comment]
> 跑一下adb kill-server再试试？

```
C:\Users\Administrator>adb kill-server

C:\Users\Administrator>
```
跑完就是这样的

**Comment by nladuo** [comment]
```
adb kill-server
adb devices
python -m uiautomator2 init
```
这样试试。

**Comment by poemon** [comment]
```
(py39) C:\Users\Administrator>adb kill-server

(py39) C:\Users\Administrator>adb devices
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
List of devices attached
emulator-5554   device


(py39) C:\Users\Administrator>python -m uiautomator2 init
[I 230628 18:00:28 init:156] uiautomator2 version: 2.16.23
[I 230628 18:00:28 init:373] Install minicap, minitouch
[D 230628 18:00:28 init:59] Use cached assets: C:\Users\Administrator\.uiautomator2\cache\minitouch-69336c8f34\minitouch
[D 230628 18:00:28 init:238] Push to /data/local/tmp/minitouch:0755
[D 230628 18:00:28 init:59] Use cached assets: C:\Users\Administrator\.uiautomator2\cache\minicap.so-0750876ce8\minicap.so
[D 230628 18:00:28 init:238] Push to /data/local/tmp/minicap.so:0755
[D 230628 18:00:28 init:59] Use cached assets: C:\Users\Administrator\.uiautomator2\cache\minicap-3d0b86b17d\minicap
[D 230628 18:00:28 init:238] Push to /data/local/tmp/minicap:0755
[D 230628 18:00:28 init:256] apk-debug package-info: {'package_name': 'com.github.uiautomator', 'version_name': '2.3.3', 'version_code': 2003003, 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2023, 6, 28, 0, 33, 9), 'last_update_time': datetime.datetime(2023, 6, 28, 0, 33, 9), 'signature': 'ae17cd86], past signatures:['}
[D 230628 18:00:28 init:257] apk-debug-test package-info: {'package_name': 'com.github.uiautomator.test', 'version_name': 'null', 'version_code': 0, 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2023, 6, 28, 0, 33, 9), 'last_update_time': datetime.datetime(2023, 6, 28, 0, 33, 9), 'signature': 'ae17cd86], past signatures:['}
[I 230628 18:00:28 init:391] Already installed com.github.uiautomator apks
[D 230628 18:00:28 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--stop')
[D 230628 18:00:28 init:295] Real version: [0, 10, 0], Expect version: [0, 10, 0]
[D 230628 18:00:28 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--nouia', '-d', '--addr', '127.0.0.1:7912')
[I 230628 18:00:28 init:350] Check atx-agent version
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\py39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\anaconda3\envs\py39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\uiautomator2\__main__.py", line 289, in <module>
    main()
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\uiautomator2\__main__.py", line 279, in main
    actions[args.subparser](args)
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\uiautomator2\__main__.py", line 36, in cmd_init
    init.install()
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\uiautomator2\init.py", line 393, in install
    self.setup_atx_agent()
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\uiautomator2\init.py", line 351, in setup_atx_agent
    self.check_atx_agent_version()
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\retry\api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\uiautomator2\init.py", line 358, in check_atx_agent_version
    port = self._device.forward_port(7912)
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\adbutils\_device.py", line 244, in forward_port
    for f in self.forward_list():
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\adbutils\_device.py", line 252, in forward_list
    c = self.open_transport("list-forward")
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\adbutils\_device.py", line 89, in open_transport
    c.check_okay()
  File "C:\ProgramData\anaconda3\envs\py39\lib\site-packages\adbutils\_adb.py", line 134, in check_okay
    raise AdbError(self.read_string_block())
adbutils.errors.AdbError: unknown host service
```

还是不行的 ，我是在anaconda里新建的一个python3.9的环境

**Comment by nladuo** [comment]
应该是adb的问题。你试试搜搜：adbutils.errors.AdbError: unknown host service 相关的。

这个issue说要换最新版的adb：https://github.com/openatx/uiautomator2/issues/334
